# install environment with `conda env create -f environment.yml`
# update environment with `conda env update --name myenv -f environment.yml --prune` (see https://stackoverflow.com/a/43873901)
name: swd
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pytorch::pytorch 
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch-cuda=11.8
  - pip
  - pip:
    - dill
    - tqdm
    - scipy
    - numpy
    - pandas
    - wandb
    - param
    - pillow
    - mashumaro
    - notebook
    - matplotlib
    - ruamel.yaml
    - scikit-learn
    - tensorboard
    - ipywidgets
    - git+https://github.com/Tigxy/tbparser.git
    - git+https://github.com/Tigxy/recommender-metrics.git
